spring.application.name=RestaurantManagement
spring.datasource.url=jdbc:mysql://localhost:3306/restaurantdb?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
app.jwt.secret=lms-super-secret-key-must-be-at-least-256-bits-long-okay
app.jwt.expiration-ms=86400000
# Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=trushika.basude@coditas.com
spring.mail.password=kmrw pyzl pbiv tndo
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

