spring.application.name=RestaurantManagement
spring.datasource.url=jdbc:mysql://localhost:3306/restaurantdb?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
app.jwt.secret=lms-super-secret-key-must-be-at-least-256-bits-long-okay
app.jwt.expiration-ms=86400000

